# Generated by Django 3.0.7 on 2020-06-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fruit', 'fruit'), ('vegetable', 'vegetable'), ('other', 'other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('guid', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('has_died', models.BooleanField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('balance_in_cents', models.IntegerField(default=0)),
                ('picture_url', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('greeting', models.TextField()),
                ('gender_code', models.SmallIntegerField(choices=[(0, 'Not known'), (1, 'Male'), (2, 'Female'), (9, 'Not applicable')])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizens.Address')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizens.Company')),
                ('eye_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citizens.EyeColor')),
                ('favourite_food', models.ManyToManyField(to='citizens.Food')),
                ('friends', models.ManyToManyField(to='citizens.Citizen')),
                ('tags', models.ManyToManyField(to='citizens.Tag')),
            ],
        ),
    ]
